[project]
name = "imgrep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.0.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
# https://docs.astral.sh/uv/guides/integration/pytorch/#__tabbed_1_5
